; generated by build.py
CreateDirectory "$INSTDIR\bin"
File "/oname=$INSTDIR\app.ico" "D:\Users\gglas\Devel\Utils\NsisInstallerTemplate\NsisInstaller\test-files\app.ico"
File "/oname=$INSTDIR\LICENSE.txt" "D:\Users\gglas\Devel\Utils\NsisInstallerTemplate\NsisInstaller\test-files\LICENSE.txt"
File "/oname=$INSTDIR\bin\test.txt" "D:\Users\gglas\Devel\Utils\NsisInstallerTemplate\NsisInstaller\test-files\bin\test.txt"
